benchmark_root: /home/s2758621/Continual_VLA_RL/LIBERO/libero/libero
bddl_files: /home/s2758621/Continual_VLA_RL/LIBERO/libero/libero/bddl_files
init_states: /home/s2758621/Continual_VLA_RL/LIBERO/libero/libero/init_files
datasets: /home/s2758621/Continual_VLA_RL/LIBERO/datasets
assets: /home/s2758621/Continual_VLA_RL/LIBERO/libero/libero/assets
