assets: ./LIBERO/libero/libero/./assets
bddl_files: ./LIBERO/libero/libero/./bddl_files
benchmark_root: ./LIBERO/libero/libero
datasets: ./LIBERO/libero/libero/../datasets
init_states: ./LIBERO/libero/libero/./init_files
